EPS = 1e-6  #TODO: duplicated

AREA_LOG_EPS = 1e-6   #TODO duplicated
MIN_VALID_BOX_AREA = 1.0

AREA_PERCENTILE_EPS = 1e-12

LOG_AREA_HISTOGRAM_NUM_BINS = 32
AREA_HISTOGRAM_NUM_BINS = 32

AREA_HISTOGRAM_PEAK_PROMINENCE = 1
AREA_HISTOGRAM_VALLEY_PROMINENCE = 1
AREA_HISTOGRAM_MIN_DISTANCE_BINS = 1

LOG_AREA_GMM_COMPONENTS = 2
LOG_AREA_GMM_RANDOM_STATE = 0
LOG_AREA_GMM_COVARIANCE_TYPE = "full"